doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        driver_options:
            # Disable SSL
            1002: "SET SESSION sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''))"
